<?php

define('ADDRESS', 'address');
define('AVAILABLE', 'available');
define('AWAY', 'away');
define('AWAY_POINT', 'awayPoint');
define('BIRTHDAY', 'birthday');
define('BUDGET', 'budget');
define('CITY', 'city');
define('CREATED_AT', 'createdAt');
define('DATA', 'data');
define('DATE', 'date');
define('DATE_FORMAT', 'd/m/Y H:i');
define('DB_USERS_TABLE', 'users');
define('DB_GAME_TABLE', 'game');
define('DB_TOURNAMENT_TABLE', 'tournament');
define('DISTRICT', 'district');
define('DRAWS', 'draws');
define('DRAW_TITLE', 'drawTitle');
define('EQUAL_SIGN', '=');
define('EMAIL', 'email');
define('ERROR', 'error');
define('FIELDS_VALIDATION_FAILED', 'Alanları doğrulama hatası');
define('FIXTURE_ID', 'fixtureId');
define('GAME_ID', 'gameId');
define('HOLDER', 'holder');
define('HOLDER_ID', 'holderId');
define('HOME', 'home');
define('HOME_POINT', 'homePoint');
define('IBAN', 'iban');
define('IDENTIFIER', 'id');
define('INVALID_EMAIL_OR_PASSWORD', 'Geçersiz email veya şifre');
define('LOGGED_IN_SUCCESSFULLY', 'Oturum başarıyla açıldı');
define('LOGGED_OUT_SUCCESSFULLY', 'Oturum başarıyla kapatıldı');
define('LOSER', 'loser');
define('MATCHES', 'matches');
define('MESSAGE', 'message');
define('NAME', 'name');
define('PARTICIPANT_COUNT', 'participantCount');
define('PASSWORD', 'password');
define('PASSWORD_CONFIRMATION', 'passwordConfirmation');
define('PASSWORD_VALIDATION_FAILED', 'Şifreleri doğrulama hatası');
define('PERMISSION_DENIED', 'Bu işlem için izniniz yok');
define('PICTURE', 'picture');
define('PHONE', 'phone');
define('PROMOTION', 'promotion');
define('RANKING', 'ranking');
define('REMEMBER_TOKEN', 'remember_token');
define('SEX', 'sex');
define('START_DATE', 'startDate');
define('START_TIME', 'startTime');
define('STATE', 'state');
define('STATUS', 'status');
define('STATUS_CODE', 'status_code');
define('SUCCESS', 'success');
define('SURNAME', 'surname');
define('THIS_EMAIL_ALREADY_EXIST', 'Bu email zaten mevcut');
define('THIS_USERNAME_ALREADY_EXIST', 'Bu kullanıcı ismi zaten mevcut');
define('TICKET', 'ticket');
define('TOURNAMENT_ID', 'tournamentId');
define('TOURNAMENT_TYPE', 'tournamentType');
define('TYPE', 'type');
define('UPDATED_AT', 'updatedAt');
define('USERNAME', 'username');
define('USER_DOES_NOT_EXIST', 'Böyle bir kullanıcı yok');
define('USER_REGISTERED_SUCCESSFULLY', 'Kullanıcı başarıyla kaydedildi');
define('WINNER', 'winner');
