<?php

define('ADDRESS', 'address');
define('ATTENDED_SUCCESSFULLY', 'Başarıyla katılım sağlandı');
define('ALREADY_ATTENDED', 'Zaten bu tunuvaya katıldın');
define('AVAILABLE', 'available');
define('AWAY', 'away');
define('AWAY_POINT', 'awayPoint');
define('BIRTHDAY', 'birthday');
define('BUDGET', 'budget');
define('CITY', 'city');
define('CREATED_AT', 'createdAt');
define('CURRENT_PARTICIPANTS', 'currentParticipants');
define('DATA', 'data');
define('DATE', 'date');
define('DATE_FORMAT', 'd/m/Y H:i');
define('DAYS', 'days');
define('DB_FIXTURE_TABLE', 'fixture');
define('DB_GAME_TABLE', 'game');
define('DB_PARTICIPANT_TABLE', 'participant');
define('DB_TOURNAMENT_TABLE', 'tournament');
define('DB_USERS_TABLE', 'users');
define('DID_NOT_ATTENDED', 'Bu turnuvaya zaten katılmadın');
define('DISTRICT', 'district');
define('DRAWS', 'draws');
define('DRAW_TITLE', 'drawTitle');
define('EARNINGS', 'earnings');
define('EQUAL_SIGN', '=');
define('EMAIL', 'email');
define('ERROR', 'error');
define('EXPIRED_TOURNAMENT', 'Bu turnuvaya kayıt süresi dolmuştur');
define('FIELDS_VALIDATION_FAILED', 'Alanları doğrulama hatası');
define('FIXTURE', 'fixture');
define('FIXTURE_ID', 'fixtureId');
define('GAME_ID', 'gameId');
define('GAMER', 'gamer');
define('HOLDER', 'holder');
define('HOLDER_ID', 'holderId');
define('HOME', 'home');
define('HOME_POINT', 'homePoint');
define('IBAN', 'iban');
define('IDENTIFIER', 'id');
define('INVALID_DATE', 'Geçersiz zaman');
define('INVALID_EMAIL_OR_PASSWORD', 'Geçersiz email veya şifre');
define('INVALID_PAYMENT_TYPE', 'Geçersiz ödeme tipi');
define('KNOCK_OUT', 'knock_out');
define('LEFT_TOURNAMENT_SUCCESSFULLY', 'Turnuvadan başarıyla ayrıldın');
define('LOGGED_IN_SUCCESSFULLY', 'Oturum başarıyla açıldı');
define('LOGGED_OUT_SUCCESSFULLY', 'Oturum başarıyla kapatıldı');
define('LOSER', 'loser');
define('MATCHES', 'matches');
define('MAXIMUM_PARTICIPANTS_COUNT_LIMIT', 'Turnuva katılımcı sayısı limiti dolmuştur');
define('MESSAGE', 'message');
define('MONEY', 'money');
define('MIN_AMOUNT', 15);
define('NAME', 'name');
define('NEW_', 'new');
define('TOURNAMENT_STATUS_ACTIVE', 1);
define('TOURNAMENT_STATUS_CLOSE', 0);
define('TOURNAMENT_STATUS_OPEN', 2);
define('PARTICIPANT_COUNT', 'participantCount');
define('PARTICIPANT_ID', 'participantId');
define('PASSWORD', 'password');
define('PASSWORD_CONFIRMATION', 'passwordConfirmation');
define('PASSWORD_VALIDATION_FAILED', 'Şifreleri doğrulama hatası');
define('PAYMENT_AMOUNT', 'paymentAmount');
define('PAYMENT_TYPE', 'paymentType');
define('PERMISSION_DENIED', 'Bu işlem için izniniz yok');
define('PICTURE', 'picture');
define('PHONE', 'phone');
define('PROMOTION', 'promotion');
define('PLAYER', 'player');
define('POINT', 'point');
define('RANKING', 'ranking');
define('REMEMBER_TOKEN', 'remember_token');
define('SEX', 'sex');
define('START_DATE', 'startDate');
define('START_TIME', 'startTime');
define('STATE', 'state');
define('STATUS', 'status');
define('STATUS_CODE', 'status_code');
define('SUCCESS', 'success');
define('SURNAME', 'surname');
define('THIS_EMAIL_ALREADY_EXIST', 'Bu email zaten mevcut');
define('THIS_USERNAME_ALREADY_EXIST', 'Bu kullanıcı ismi zaten mevcut');
define('TICKET', 'ticket');
define('TIMESTAMP_FORMAT', 'Y-m-d H:i:s');
define('TOURNAMENT_CREATED_SUCCESSFULLY', 'Turnuva başarıyla oluşturuldu');
define('TOURNAMENT_ID', 'tournamentId');
define('TOURNAMENT_TYPE', 'tournamentType');
define('TYPE', 'type');
define('UPDATED_AT', 'updatedAt');
define('USERNAME', 'username');
define('USER_DOES_NOT_EXIST', 'Böyle bir kullanıcı yok');
define('USER_REGISTERED_SUCCESSFULLY', 'Kullanıcı başarıyla kaydedildi');
define('WINNER', 'winner');
