<?php

define('ACTIVE_STATUS_COUNT', 'activeStatusCount');
define('ADDRESS', 'address');
define('ADMIN', 'admin');
define('ATTENDED', 'attended');
define('ATTENDED_SUCCESSFULLY', 'Başarıyla katılım sağlandı');
define('ALREADY_ATTENDED', 'Zaten bu tunuvaya katıldın');
define('ALREADY_HAVE_TOURNAMENT_ON_THIS_DATE', 'Bu tarihte zaten bir turnuvan var');
define('AMOUNT', 'amount');
define('AUTHENTICATION_ERROR', 'Kimlik doğrulama hatası oluştu');
define('AVAILABLE', 'available');
define('AWAY', 'away');
define('AWAY_ID', 'awayId');
define('AWAY_POINT', 'awayPoint');
define('BIRTHDAY', 'birthday');
define('BUDGET', 'budget');
define('CANCEL_STATUS_COUNT', 'cancelStatusCount');
define('CHANNEL', 'channel');
define('CITY', 'city');
define('CLOSE_STATUS_COUNT', 'closeStatusCount');
define('CREATED_AT', 'createdAt');
define('COMMISSION_PERCENTAGE', 6);
define('COUNT', 'count');
define('CURRENT_PARTICIPANTS', 'currentParticipants');
define('CURRENCY', 'currency');
define('DATA', 'data');
define('DATE', 'date');
define('DATE_FORMAT', 'd/m/Y H:i');
define('DAY_MONTH', 'd/m');
define('DAYS', 'days');
define('DB_FINANCE_TABLE', 'finance');
define('DB_FIXTURE_TABLE', 'fixture');
define('DB_GAME_TABLE', 'game');
define('DB_PARTICIPANT_TABLE', 'participant');
define('DB_MATCH_TABLE', 'match');
define('DB_TOURNAMENT_TABLE', 'tournament');
define('DB_USERS_TABLE', 'users');
define('DEPOSIT', 'deposit');
define('DEVELOPER', 'developer');
define('DID_NOT_ATTENDED', 'Bu turnuvaya zaten katılmadın');
define('DIFFERENCE', 'difference');
define('DISTRICT', 'district');
define('DRAWS', 'draws');
define('DRAW_TITLE', 'drawTitle');
define('EARNINGS', 'earnings');
define('EQUAL_SIGN', '=');
define('EQUAL_OR_GREATER_SIGN', '>=');
define('EQUAL_OR_LESS_SIGN', '<=');
define('EMAIL', 'email');
define('ERROR', 'error');
define('EXPIRED_TOURNAMENT', 'Bu turnuvaya kayıt süresi dolmuştur');
define('FIELDS_VALIDATION_FAILED', 'Alanları doğrulama hatası');
define('FINAL_', 'final');
define('FINANCE', 'finance');
define('FINANCE_ID', 'financeId');
define('FINANCE_REPORT', 'finance');
define('FINANCE_STATUS_WAITING', 1);
define('FINANCE_STATUS_APPROVED', 0);
define('FIXTURE', 'fixture');
define('FIXTURE_ID', 'fixtureId');
define('GAME', 'game');
define('GAME_ID', 'gameId');
define('GAME_IMAGE', 'gameImage');
define('GAME_NAME', 'gameName');
define('GAME_TYPE', 'gameType');
define('GAMER', 'gamer');
define('GOAL', 'goal');
define('HOLDER', 'holder');
define('HOLDER_ID', 'holderId');
define('HOME', 'home');
define('HOME_ID', 'homeId');
define('HOME_POINT', 'homePoint');
define('HOUR_MINUTE', 'H:i');
define('IBAN', 'iban');
define('IDENTIFIER', 'id');
define('IMAGE', 'image');
define('INVALID_DATE', 'Geçersiz zaman');
define('INVALID_EMAIL_OR_PASSWORD', 'Geçersiz email veya şifre');
define('INVALID_PAYMENT_TYPE', 'Geçersiz ödeme tipi');
define('KNOCK_OUT', 'knock_out');
define('LABEL', 'label');
define('LEFT_TOURNAMENT_SUCCESSFULLY', 'Turnuvadan başarıyla ayrıldın');
define('LIKE_SIGN', 'like');
define('LOGGED_IN_SUCCESSFULLY', 'Oturum başarıyla açıldı');
define('LOGGED_OUT_SUCCESSFULLY', 'Oturum başarıyla kapatıldı');
define('LOSER', 'loser');
define('LOSER_ID', 'loserId');
define('MATCH', 'match');
define('MATCHES', 'matches');
define('MATCH_ID', 'matchId');
define('MATCH_RESULT_UPDATED_SUCCESSFULLY', 'Maç sonucu başarıyla güncellendi');
define('MAX_AVATAR_COUNT', 31);
define('MAX_EARNINGS', 92);
define('MAXIMUM_PARTICIPANTS_COUNT_LIMIT', 'Turnuva katılımcı sayısı limiti dolmuştur');
define('MESSAGE', 'message');
define('MONEY', 'money');
define('MIN_AVATAR_COUNT', 1);
define('MIN_AMOUNT', 15);
define('MOST_PLAYED_REPORT', 'most-played');
define('MUST_BE_ONE_WINNER', 'Bir galip belirlemeniz lazım');
define('NAME', 'name');
define('NEW_', 'new');
define('NEW_PASSWORD', 'newPassword');
define('NO_REPLY', 'no-reply@ozelden.com');
define('NOT_EQUAL_SIGN', '!=');
define('NOTE', 'note');
define('NOTIFICATION_REPORT', 'notification');
define('ONESIGNAL_DEVICE_ID', 'onesignalDeviceId');
define('TIME', 'time');
define('THIRD_PLACE', 'third_place');
define('TOUR_ID', 'tourId');
define('TOUR_NAME', 'tourName');
define('TOURNAMENT_STATUS_ACTIVE', 1);
define('TOURNAMENT_STATUS_CANCEL', 3);
define('TOURNAMENT_STATUS_CLOSE', 0);
define('TOURNAMENT_STATUS_OPEN', 2);
define('PARTICIPANT_COUNT', 'participantCount');
define('PARTICIPANT_ID', 'participantId');
define('PARTICIPANT', 'participant');
define('PARTICIPANTS', 'participants');
define('PASSWORD', 'password');
define('PASSWORD_CONFIRMATION', 'passwordConfirmation');
define('PASSWORD_UPDATED_SUCCESSFULLY', 'Şifre başarıyla güncellendi');
define('PASSWORD_VALIDATION_FAILED', 'Şifreleri doğrulama hatası');
define('PAYMENT_AMOUNT', 'paymentAmount');
define('PAYMENT_TYPE', 'paymentType');
define('PERMISSION_DENIED', 'Bu işlem için izniniz yok');
define('PICTURE', 'picture');
define('PHONE', 'phone');
define('PREVIOUS_RANKING', 'previousRanking');
define('PRICE', 'price');
define('PROMOTION', 'promotion');
define('PLATFORMS', 'platforms');
define('PLAYER', 'player');
define('PLAYING_TYPE', 'playingType');
define('POINT', 'point');
define('RANKING', 'ranking');
define('RANKING_REPORT', 'ranking');
define('REFERENCE_CODE', 'referenceCode');
define('REPORT_TYPE', 'reportType');
define('REMEMBER_TOKEN', 'remember_token');
define('RESULT_ALREADY_SET', 'Zaten sonuç belirlediniz');
define('SEMI_FINAL', '1/2');
define('SETTINGS_UPDATED_SUCCESSFULLY', 'Ayarlar başarıyla güncellendi');
define('SEX', 'sex');
define('START_DATE', 'startDate');
define('START_TIME', 'startTime');
define('STATE', 'state');
define('STATUS', 'status');
define('STATUS_CODE', 'status_code');
define('STATUS_MUST_BE_ACTIVE_FOR_CHANGE', 'Değişiklik yapabilmek için turnuva durumu aktif olmalıdır');
define('SUCCESS', 'success');
define('SURNAME', 'surname');
define('THIS_EMAIL_ALREADY_EXIST', 'Bu email zaten mevcut');
define('THIS_USERNAME_ALREADY_EXIST', 'Bu kullanıcı ismi zaten mevcut');
define('TICKET', 'ticket');
define('TICKET_TR', 'turnuva bileti');
define('TIMELINE_REPORT', 'timeline');
define('REPORT_CREATED_SUCCESSFULLY', 'Rapor başarıyla oluşturuldu');
define('TIMESTAMP_FORMAT', 'Y-m-d H:i:s');
define('TOURNAMENT', 'tournament');
define('TOURNAMENT_CREATED_SUCCESSFULLY', 'Turnuva başarıyla oluşturuldu');
define('TOURNAMENT_ID', 'tournamentId');
define('TOURNAMENT_TYPE', 'tournamentType');
define('TOURNAMENT_RANKING', 'tournamentRanking');
define('TOTAL_COUNT', 'totalCount');
define('TURKISH_LIRA', '₺');
define('TYPE', 'type');
define('OPEN_STATUS_COUNT', 'openStatusCount');
define('UPDATED_AT', 'updatedAt');
define('USER_ACTIVATED', 'Kullanıcı aktif edildi');
define('USER_STATE_ACTIVE', 1);
define('USER_STATE_DISABLE', 0);
define('USERNAME', 'username');
define('USER_ID', 'userId');
define('USER_DOES_NOT_EXIST', 'Böyle bir kullanıcı yok');
define('USER_REGISTERED_SUCCESSFULLY', 'Kullanıcı başarıyla kaydedildi');
define('WELCOME_EMAIL', 'welcomeEmail');
define('WINNER', 'winner');
define('WINNER_ID', 'winnerId');
